version: '3'

services:
  app:
   image: lab4
   ports:
     - 8000:8000
   environment:
     - SERVICE_PORTS=8000
   deploy:
     replicas: 5
     placement:
       constraints: [node.role == worker]
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
  redis:
    image: redis:alpine

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - app
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    deploy:
      placement:
        constraints: [node.role == manager]
